//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ../ScratchScript.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ScratchScriptParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IScratchScriptListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ScratchScriptParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ScratchScriptParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.topLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelStatement([NotNull] ScratchScriptParser.TopLevelStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.topLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelStatement([NotNull] ScratchScriptParser.TopLevelStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] ScratchScriptParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] ScratchScriptParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] ScratchScriptParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] ScratchScriptParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.eventStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventStatement([NotNull] ScratchScriptParser.EventStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.eventStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventStatement([NotNull] ScratchScriptParser.EventStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] ScratchScriptParser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] ScratchScriptParser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.variableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarationStatement([NotNull] ScratchScriptParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.variableDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarationStatement([NotNull] ScratchScriptParser.VariableDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.procedureCallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureCallStatement([NotNull] ScratchScriptParser.ProcedureCallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.procedureCallStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureCallStatement([NotNull] ScratchScriptParser.ProcedureCallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.procedureDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureDeclarationStatement([NotNull] ScratchScriptParser.ProcedureDeclarationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.procedureDeclarationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureDeclarationStatement([NotNull] ScratchScriptParser.ProcedureDeclarationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] ScratchScriptParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] ScratchScriptParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileStatement([NotNull] ScratchScriptParser.WhileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.whileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileStatement([NotNull] ScratchScriptParser.WhileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfStatement([NotNull] ScratchScriptParser.ElseIfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfStatement([NotNull] ScratchScriptParser.ElseIfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImportStatement([NotNull] ScratchScriptParser.ImportStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.importStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImportStatement([NotNull] ScratchScriptParser.ImportStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.attributeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAttributeStatement([NotNull] ScratchScriptParser.AttributeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.attributeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAttributeStatement([NotNull] ScratchScriptParser.AttributeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] ScratchScriptParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] ScratchScriptParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRepeatStatement([NotNull] ScratchScriptParser.RepeatStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.repeatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRepeatStatement([NotNull] ScratchScriptParser.RepeatStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] ScratchScriptParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] ScratchScriptParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] ScratchScriptParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] ScratchScriptParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.procedureArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureArgument([NotNull] ScratchScriptParser.ProcedureArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.procedureArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureArgument([NotNull] ScratchScriptParser.ProcedureArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>parenthesizedExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthesizedExpression([NotNull] ScratchScriptParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthesizedExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthesizedExpression([NotNull] ScratchScriptParser.ParenthesizedExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>constantExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpression([NotNull] ScratchScriptParser.ConstantExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>constantExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpression([NotNull] ScratchScriptParser.ConstantExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifierExpression([NotNull] ScratchScriptParser.IdentifierExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>identifierExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifierExpression([NotNull] ScratchScriptParser.IdentifierExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>procedureCallExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcedureCallExpression([NotNull] ScratchScriptParser.ProcedureCallExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>procedureCallExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcedureCallExpression([NotNull] ScratchScriptParser.ProcedureCallExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryBooleanExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryBooleanExpression([NotNull] ScratchScriptParser.BinaryBooleanExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryBooleanExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryBooleanExpression([NotNull] ScratchScriptParser.BinaryBooleanExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpression([NotNull] ScratchScriptParser.NotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>notExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpression([NotNull] ScratchScriptParser.NotExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryCompareExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryCompareExpression([NotNull] ScratchScriptParser.BinaryCompareExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryCompareExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryCompareExpression([NotNull] ScratchScriptParser.BinaryCompareExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryMultiplyExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryMultiplyExpression([NotNull] ScratchScriptParser.BinaryMultiplyExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryMultiplyExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryMultiplyExpression([NotNull] ScratchScriptParser.BinaryMultiplyExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>unaryAddExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryAddExpression([NotNull] ScratchScriptParser.UnaryAddExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>unaryAddExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryAddExpression([NotNull] ScratchScriptParser.UnaryAddExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>binaryAddExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBinaryAddExpression([NotNull] ScratchScriptParser.BinaryAddExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>binaryAddExpression</c>
	/// labeled alternative in <see cref="ScratchScriptParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBinaryAddExpression([NotNull] ScratchScriptParser.BinaryAddExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.multiplyOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplyOperators([NotNull] ScratchScriptParser.MultiplyOperatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.multiplyOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplyOperators([NotNull] ScratchScriptParser.MultiplyOperatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.addOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddOperators([NotNull] ScratchScriptParser.AddOperatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.addOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddOperators([NotNull] ScratchScriptParser.AddOperatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.compareOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareOperators([NotNull] ScratchScriptParser.CompareOperatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.compareOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareOperators([NotNull] ScratchScriptParser.CompareOperatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.booleanOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBooleanOperators([NotNull] ScratchScriptParser.BooleanOperatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.booleanOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBooleanOperators([NotNull] ScratchScriptParser.BooleanOperatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.assignmentOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentOperators([NotNull] ScratchScriptParser.AssignmentOperatorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.assignmentOperators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentOperators([NotNull] ScratchScriptParser.AssignmentOperatorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] ScratchScriptParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] ScratchScriptParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] ScratchScriptParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] ScratchScriptParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] ScratchScriptParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] ScratchScriptParser.CommentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ScratchScriptParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolean([NotNull] ScratchScriptParser.BooleanContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ScratchScriptParser.boolean"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolean([NotNull] ScratchScriptParser.BooleanContext context);
}
